name: sdt-actions
run-name: build & test
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Rename .env-test to .env
        run: mv .env-test .env
      - name: npm install and test
        run: |
          npm install
          npm run test test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage
      - name: Barecheck - Code Coverage
        uses: barecheck/code-coverage-action@v1.0.0
