name: sdt-actions
run-name: build & test
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Rename .env-test to .env
        run: mv .env-test .env
      - name: npm install and test
        run: |
          npm install
          npm run test test
      - name: cobertura - Code Coverage
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage/cobertura-coverage.xml
          minimum_coverage: 75
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage
